<?php

namespace Kub\EDTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository
{

	public function getCurrentCoursOf(\Kub\UserBundle\Entity\Professeur $professeur)
	{
		$qb = $this->createQueryBuilder('c')
			->join('c.professeur', 'p')
			->addSelect('p')
			->join('c.groupes', 'g')
			->addSelect('g')
			->join('c.horaires', 'h')
			->addSelect('h')
			->join('h.jour', 'j')
			->addSelect('j')
			->join('h.semaines', 's')
			->addSelect('s')
			
			->where('p.id = :id')
			->setParameter('id', $professeur->getId())
			->andWhere('j.id = :day_id')
			->setParameter('day_id', date('N'))
			->andWhere(' CURRENT_TIME() BETWEEN h.debut AND h.fin')
		;

			$qb->andWhere( $qb->expr()->in( 's.id', date('W')) )
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

}
