<?php

namespace Kub\EDTBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\EDTBundle\Entity\Horaire ;

/**
 * HoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireRepository extends EntityRepository
{

	public function countConflictualCours(Horaire $horaires)
	{
		$query = $this->_em->createQuery(
			"SELECT COUNT(h) 
			 FROM KubEDTBundle:Horaire h 
			 JOIN h.cours c 
			 JOIN c.groupes g 
			 JOIN g.eleves e 
			 JOIN e.groupes g2 
			 JOIN g2.cours c2 
			 JOIN c2.horaires h2
			 JOIN h2.debut 
			"
		);
  		
  		return $query->getOneScalarResult();
	}

}
