<?php

namespace Kub\EDTBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\EDTBundle\Entity\Horaire ;

/**
 * HoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireRepository extends EntityRepository
{

	public function findConflictualCours(Horaire $horaire)
	{
		$query = $this->_em->createQuery(
			"SELECT h, c, g
			 FROM KubEDTBundle:Horaire h 
			 JOIN h.cours c 
			 JOIN c.groupes g
			 JOIN g.eleves e
			 JOIN h.jour j

			 WHERE h.id != :id 
			 AND 
			 (
				 (
				 	h.debut BETWEEN :debut AND :fin
				 OR h.fin   BETWEEN :debut AND :fin 
				 ) OR (
				     :debut  BETWEEN h.debut AND h.fin
				 AND :fin    BETWEEN h.debut AND h.fin
				 )  
			 )
			  AND
			  j.id = :jour
			"
		)
		->setParameter('id', $horaire->getId())
		->setParameter('debut', $horaire->getDebut())
		->setParameter('fin', $horaire->getFin())
		->setParameter('jour', $horaire->getJour()->getId())
		;	

  		return $query->getResult();
	}

}
