<?php

namespace Kub\AbsenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppelRepository extends EntityRepository
{

	public function findOneOrNullByCoursAndSemaine(\Kub\EDTBundle\Entity\Cours $cours, \Kub\EDTBundle\Entity\Semaine $semaine)
	{
		$qb = $this->createQueryBuilder('a')
			->join('a.cours', 'c')
			->addSelect('c')
			->join('a.semaine', 's')
			->addSelect('s')

			->where('s.id = :sid')
			->setParameter('sid', $semaine->getId())
			->where('c.id = :cid')
			->setParameter('cid', $semaine->getId())
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

}
