parameters:
#    kub_classe.example.class: Kub\ClasseBundle\Example

services:
#    kub_classe.example:
#        class: %kub_classe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
