<?php

namespace Kub\ArianeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\UserBundle\Entity\Eleve ;

/**
 * FilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilRepository extends EntityRepository
{
}
