<?php

namespace Kub\ArianeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\UserBundle\Entity\Eleve ;

/**
 * FilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilRepository extends EntityRepository
{

	public function findByUser($username)
	{
		$qb = $this->createQueryBuilder("f")
			->leftJoin('f.posts', 'p')
			->addSelect('p')
			->leftJoin('p.commentaires', 'c')
			->addSelect('c')
			->join('f.eleve', 'e')
			->where('e.username = :username')
			->setParameter("username", $username )
			->orderBy('p.dateAjout', 'DESC')
		;

		return $qb->getQuery()->getSingleResult();
	}

}
