<?php

namespace Kub\ArianeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\UserBundle\Entity\Eleve ;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function findByUser($username)
	{
		$qb = $this->createQueryBuilder("p")
			->leftJoin('p.fil', 'f')
			->join('f.eleve', 'e')
			->where('e.username = :username')
			->setParameter("username", $username )
			->orderBy('p.dateAjout', 'DESC')
		;

		return $qb->getQuery()->getResult();
	}

}
