kub_ressource_homepage:
    pattern:  /
    defaults: { _controller: KubRessourceBundle:Default:index }

kub_ressource_add:
    pattern:  /add
    defaults: { _controller: KubRessourceBundle:Default:add }