kub_ressource_homepage:
    pattern:  /
    defaults: { _controller: KubRessourceBundle:Default:index }

kub_ressource_edit:
    pattern:  /modifier/{id}
    defaults: { _controller: KubRessourceBundle:Default:edit }
    requirements:
        id: \d+

kub_ressource_delete:
    pattern:  /supprimer/{id}
    defaults: { _controller: KubRessourceBundle:Default:delete }
    requirements:
        id: \d+

kub_ressource_show:
    pattern:  /voir/{id}
    defaults: { _controller: KubRessourceBundle:Default:show }
    requirements:
        id: \d+


kub_ressource_add:
    pattern:  /ajouter
    defaults: { _controller: KubRessourceBundle:Default:add }

kub_ressource_propose:
    pattern:  /proposer
    defaults: { _controller: KubRessourceBundle:Default:add }


kub_ressource_validation_list:
    pattern:  /validation
    defaults: { _controller: KubRessourceBundle:Validation:index }

kub_ressource_validation_valider:
    pattern:  /validation/{id}
    defaults: { _controller: KubRessourceBundle:Validation:valider }
    requirements:
        id: \d+