<?php

namespace Kub\ClasseBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\UserBundle\Entity\Professeur ;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
	public function getGroupesOfProfesseur(Professeur $professeur)
	{
		$qb = $this->createQueryBuilder("g")
			->join('g.cours', 'c')
			->join('c.professeur', 'p')
			->where('p.id = :id')
			->setParameter('id', $professeur->getId())
			;

		return $qb->getQuery()->getResult();
	}
}
