kub_edt:
    resource: "@KubEDTBundle/Resources/config/routing.yml"
    prefix:   /

kub_classe:
    resource: "@KubClasseBundle/Resources/config/routing.yml"
    prefix:   /

kub_ressource:
    resource: "@KubRessourceBundle/Resources/config/routing.yml"
    prefix:   /

kub_casier:
    resource: "@KubCasierBundle/Resources/config/routing.yml"
    prefix:   /

kub_agenda:
    resource: "@KubAgendaBundle/Resources/config/routing.yml"
    prefix:   /

kub_absence:
    resource: "@KubAbsenceBundle/Resources/config/routing.yml"
    prefix:   /

kub_collaboration:
    resource: "@KubCollaborationBundle/Resources/config/routing.yml"
    prefix:   /

kub_ariane:
    resource: "@KubArianeBundle/Resources/config/routing.yml"
    prefix:   /

kub_notes:
    resource: "@KubNotesBundle/Resources/config/routing.yml"
    prefix:   /

kub_user:
    resource: "@KubUserBundle/Resources/config/routing.yml"
    prefix:   /

kub_home:
    resource: "@KubHomeBundle/Resources/config/routing.yml"
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /me

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /me

# fos_user_group:
#     resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#     prefix: /group