kub_user:
    resource: "@KubUserBundle/Resources/config/routing.yml"
    prefix:   /

kub_home:
    resource: "@KubHomeBundle/Resources/config/routing.yml"
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /me

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /me