fos_user:
    db_driver: orm
    firewall_name: main
    user_class: EVN\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
  users:
    eleve:
        entity: 
          class: EVN\UserBundle\Entity\Eleve
        profile:
          form:
            type: EVN\UserBundle\Form\Type\ProfileEleveFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
