ariane_post_add:
    pattern: /ajouter
    defaults: { _controller: KubArianeBundle:Post:add }

ariane_post_edit:
    pattern: /editer/{id}
    defaults: { _controller: KubArianeBundle:Post:edit }
    requirements: 
        id: \d+

ariane_post_delete:
    pattern: /supprimer/{id}
    defaults: { _controller: KubArianeBundle:Post:delete }
    requirements: 
        id: \d+

ariane_homepage:
    pattern: /{username}
    defaults: { _controller: KubArianeBundle:Default:index,  username: null }

ariane_commentaire_add:
    pattern: /{post}/comment/ajouter
    defaults: { _controller: KubArianeBundle:Commentaire:add }
    requirements: 
        id: \d+

ariane_commentaire_delete:
    pattern: /comment/{commentaire}/supprimer
    defaults: { _controller: KubArianeBundle:Commentaire:delete }
    requirements: 
        id: \d+