ariane_homepage:
    pattern: /{username}
    defaults: { _controller: KubArianeBundle:Default:index,  username: null }

ariane_post_add:
    pattern: /add
    defaults: { _controller: KubArianeBundle:Post:add }

ariane_post_edit:
    pattern: /edit/{id}
    defaults: { _controller: KubArianeBundle:Post:edit }
    requirements: 
        id: \d+

ariane_post_delete:
    pattern: /delete/{id}
    defaults: { _controller: KubArianeBundle:Post:delete }
    requirements: 
        id: \d+

ariane_commentaire_add:
    pattern: /{post}/comment/add
    defaults: { _controller: KubArianeBundle:Commentaire:add }
    requirements: 
        id: \d+

ariane_commentaire_delete:
    pattern: /comment/{commentaire}/delete
    defaults: { _controller: KubArianeBundle:Commentaire:delete }
    requirements: 
        id: \d+