parameters:
#    kub_ariane.example.class: Kub\ArianeBundle\Example

services:
#    kub_ariane.example:
#        class: %kub_ariane.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kub.ariane.formManager:
        class: Kub\ArianeBundle\Form\Manager\FormManager
        arguments: [@request, @doctrine.orm.default_entity_manager, @security.context, @form.factory, @session]
        scope: request