fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kub\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
  users:
    eleve:
        entity: 
            class: Kub\UserBundle\Entity\Eleve
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileEleveFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

    tuteur:
        entity: 
            class: Kub\UserBundle\Entity\Tuteur
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileTuteurFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

    professeur:
        entity: 
            class: Kub\UserBundle\Entity\Professeur
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileProfesseurFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

    administrateur:
        entity: 
            class: Kub\UserBundle\Entity\Administrateur
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileAdministrateurFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

services:
    kub_main.menu_builder:
        class: Kub\UserBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    kub_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kub_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu


