fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kub\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
  users:
    eleve:
        entity: 
            class: Kub\UserBundle\Entity\Eleve
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileEleveFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

    tuteur:
        entity: 
            class: Kub\UserBundle\Entity\Tuteur
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileTuteurFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

    professeur:
        entity: 
            class: Kub\UserBundle\Entity\Professeur
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileProfesseurFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

    administrateur:
        entity: 
            class: Kub\UserBundle\Entity\Administrateur
        profile:
          form:
            type: Kub\UserBundle\Form\Type\ProfileAdministrateurFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]

