user_create:
    path: /{role}/ajouter/
    defaults: { _controller: KubUserBundle:User:create }
    requirements:
        role: eleve|tuteur|administrateur|professeur

user_list:
    path: /{role}/liste/{niveau}
    defaults: { _controller: KubUserBundle:User:list, niveau: null}
    requirements:
        role: eleve|tuteur|administrateur|professeur

user_show:
    path: /{role}/{username}
    defaults: { _controller: KubUserBundle:User:show }
    requirements:
        role: eleve|tuteur|administrateur|professeur

user_edit:
    path: /{role}/{username}/editer
    defaults: { _controller: KubUserBundle:User:edit }
    requirements:
        role: eleve|tuteur|administrateur|professeur

user_delete:
    path: /{role}/{username}/supprimer
    defaults: { _controller: KubUserBundle:User:delete }
    requirements:
        role: eleve|tuteur|administrateur|professeur
