imports:
    - { resource: username_form_type.yml }

parameters:
#    Kub_user.example.class: Kub\UserBundle\Example

services:
    kub_main.menu_builder:
        class: Kub\UserBundle\Menu\MenuBuilder
        arguments: [@knp_menu.factory, @security.context, @doctrine.orm.entity_manager, @fos_message.provider]

    kub_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kub_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    kub_main.menu.compte:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kub_main.menu_builder
        factory_method: createCompteMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: compte } # The alias is what is used to retrieve the menu