services:
    fos_message.new_thread_form.factory.default:
        class : Kub\MessageBundle\FormFactory\NewThreadMessageFormFactory
        public : false"
        arguments: [@form.factory, @fos_message.new_thread_form.type, 'Kub\\MessageBundle\\FormType\\NewThreadMessageFormType', %fos_message.new_thread_form.model%, @doctrine.orm.entity_manager]