services:
    fos_message.thread_manager.default:
        class: "Kub\MessageBundle\EntityManager\ThreadManager"
        arguments: [@doctrine.orm.entity_manager, %fos_message.thread_class%, %fos_message.thread_meta_class%, @fos_message.message_manager]