imports:
    - { resource: form.yml }

parameters:
#    kub_message.example.class: Kub\MessageBundle\Example

services:
#    kub_message.example:
#        class: %kub_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
