parameters:
#    kub_messagerie.example.class: Kub\MessagerieBundle\Example

services:
#    kub_messagerie.example:
#        class: %kub_messagerie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
