parameters:
#    kub_messagerie.example.class: Kub\MessagerieBundle\Example

services:
   kub.messagerie:
       class: Kub\MessagerieBundle\Services\MessageManager
       arguments: [@doctrine.orm.default_entity_manager, @security.context]
