parameters:
#    kub_messagerie.example.class: Kub\MessagerieBundle\Example

services:
   kub.messagerie:
       class: Kub\MessagerieBundle\Services\MessageManager
       arguments: [@doctrine.orm.entity_manager, @security.context]
