kub_collaboration_organisation_index:
    pattern:  /{slug}/organisation
    defaults: { _controller: KubCollaborationBundle:Organisation:index }

kub_collaboration_organisation_create:
    pattern:  /{slug}/organisation/ajouter
    defaults: { _controller: KubCollaborationBundle:Organisation:create }

kub_collaboration_organisation_show:
    pattern:  /{projet_slug}/organisation/{tache_slug}
    defaults: { _controller: KubCollaborationBundle:Organisation:show }

kub_collaboration_organisation_edit:
    pattern:  /{projet_slug}/organisation/{tache_slug}/modifier
    defaults: { _controller: KubCollaborationBundle:Organisation:edit }

kub_collaboration_organisation_delete:
    pattern:  /{projet_slug}/organisation/{tache_slug}/supprimer
    defaults: { _controller: KubCollaborationBundle:Organisation:delete }

kub_api_collaboration_organisation_tache_check:
    pattern:  /_api/organisation/tache/check/
    defaults: { _controller: KubCollaborationBundle:Organisation:setTaskChecked }
    methods: POST

kub_api_collaboration_organisation_tache_participe:
    pattern:  /_api/organisation/tache/participer/
    defaults: { _controller: KubCollaborationBundle:Organisation:setUserParticipe }
    methods: POST