parameters:
#    evn_home.example.class: EVN\HomeBundle\Example

services:
#    evn_home.example:
#        class: %evn_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
