groupe_show:
    pattern:  /{id}/show
    defaults: { _controller: "KubUserBundle:Groupe:show" }

groupe_create:
    pattern:  /add
    defaults: { _controller: "KubUserBundle:Groupe:create" }

groupe_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KubUserBundle:Groupe:edit" }

groupe_update:
    pattern:  /{id}/update
    defaults: { _controller: "KubUserBundle:Groupe:update" }
    requirements: { _method: post|put }

groupe_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KubUserBundle:Groupe:delete" }
    requirements: { _method: post|delete }
