groupe_show:
    pattern:  /{id}/show
    defaults: { _controller: "KubUserBundle:Groupe:show" }

groupe_create:
    pattern:  /add
    defaults: { _controller: "KubUserBundle:Groupe:create" }

groupe_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KubUserBundle:Groupe:edit" }

groupe_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KubUserBundle:Groupe:delete" }
    requirements: { _method: post|delete }

groupe_list:
    pattern:  /list
    defaults: { _controller: "KubUserBundle:Groupe:list" }