edt_frequence:
    resource: "@KubEDTBundle/Resources/config/routing/frequence.yml"
    prefix: /frequence

edt_cours:
    resource: "@KubEDTBundle/Resources/config/routing/cours.yml"
    prefix: /cours

edt_homepage:
    pattern:  /agenda
    defaults: { _controller: KubEDTBundle:EDT:index }
