parameters:
    edt:
        jours:
            - lundi
            - mardi
            - mercredi
            - jeudi
            - vendredi
        horaires: 
            - 7  : [55]
            - 8  : [25, 55]
            - 9  : [05, 25, 50]
            - 10 : [05, 25]
            - 11 : [00, 25, 55]
            - 12 : [25, 55]
            - 13 : [25, 55]
            - 14 : [25]
            - 15 : [20, 55]
            - 16 : [20, 55]
            - 17 : [20]

services:
#    kub_edt.example:
#        class: %kub_edt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kub.edt.time:
        class: "Kub\EDTBundle\Services\TimeService"
        arguments: [%edt%, @doctrine.orm.entity_manager]

    validator.unique.time_edt_compatible:
        class: Kub\EDTBundle\Validator\Constraints\TimeEDTCompatibleValidator
        arguments: [@kub.edt.time]
        tags:
            - { name: validator.constraint_validator, alias: time_edt_compatible }

    validator.unique.time_edt_no_conflict:
        class: Kub\EDTBundle\Validator\Constraints\NoHoraireConflictValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: time_edt_no_conflict }
