parameters:
#    kub_absence.example.class: Kub\AbsenceBundle\Example

services:
#    kub_absence.example:
#        class: %kub_absence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
