parameters:
#    kub_notes.example.class: Kub\NotesBundle\Example

services:
#    kub_notes.example:
#        class: %kub_notes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
