<?php

namespace Kub\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

	public function findByUser($user, $offset) { 
		$qb = $this->createQueryBuilder("n")
			->leftJoin('n.auteur', 'a') 
			->addSelect('a')
			->leftJoin('n.userTarget', 'u') 
			->where('u.id = :id') 
			->setParameter('id',$user->getId())

			->orderBy('n.date', 'DESC')
			->setFirstResult($offset)
			->setMaxResults(12)
		;

		if($user->getClass() == "eleve")
		{
			$groupes_id = array('0');
			foreach ($user->getGroupes() as $key => $groupe) {
				$groupes_id[] = $groupe->getId();
			}

			$qb->leftJoin('n.groupesTarget', 'g')
			   ->orWhere( $qb->expr()->in('g.id', $groupes_id))
			;
		}

		return $qb->getQuery()->getResult();
	}

}
