kub_notes_eleve_homepage:
    pattern:  /notes
    defaults: { _controller: KubNoteBundle:Eleve:index }

kub_notes_professeur_homepage:
    pattern:  /noter/{cours}
    defaults: { _controller: KubNoteBundle:Professeur:add, cours: null }
    requirements:
        id: \d+

kub_notes_professeur_delete:
    pattern:  /noter/{note}/supprimer
    defaults: { _controller: KubNoteBundle:Professeur:delete }
    requirements:
        id: \d+

kub_notes_eleve_show:
    pattern: /eleve/{username}/notes
    defaults: { _controller: KubNoteBundle:Professeur:showEleve }