kub_notes_eleve_homepage:
    pattern:  /mesnotes
    defaults: { _controller: KubNoteBundle:Eleve:index }

kub_notes_professeur_homepage:
    pattern:  /notes
    defaults: { _controller: KubNoteBundle:Professeur:index }
    requirements:
        id: \d+

kub_notes_professeur_noter_cours:
    pattern:  /notes/cours/{cours}
    defaults: { _controller: KubNoteBundle:Professeur:noterCours }
    requirements:
        id: \d+

kub_notes_professeur_noter_groupe:
    pattern:  /notes/groupe/{groupe_id}
    defaults: { _controller: KubNoteBundle:Professeur:noterGroupe }
    requirements:
        id: \d+

kub_notes_professeur_noter_eleve:
    pattern:  /notes/eleve/{eleve}
    defaults: { _controller: KubNoteBundle:Professeur:noterEleve }

kub_notes_professeur_delete:
    pattern:  /notes/{controle}/supprimer
    defaults: { _controller: KubNoteBundle:Professeur:delete }
    requirements:
        id: \d+

kub_notes_professeur_show:
    pattern: /controle/{id}/detail
    defaults: { _controller: KubNoteBundle:Professeur:show }
    requirements:
        id: \d+

kub_notes_professeur_edit:
    pattern: /controle/{id}/editer
    defaults: { _controller: KubNoteBundle:Professeur:edit }
    requirements:
        id: \d+

kub_notes_eleve_show:
    pattern: /eleve/{username}/notes
    defaults: { _controller: KubNoteBundle:Professeur:showEleve }

kub_api_notes_eleve_get:
    pattern:  /_api/note/eleve/obtenir/
    defaults: { _controller: KubNoteBundle:Professeur:getNoteForControle }
    methods: POST