cours_create:
    pattern:  /ajouter
    defaults: { _controller: "KubEDTBundle:Cours:create" }

cours_list:
    pattern:  /
    defaults: { _controller: "KubEDTBundle:Cours:list" }

cours_delete:
    pattern:  /{id}/supprimer
    defaults: { _controller: "KubEDTBundle:Cours:delete" }
    requirements: 
        id: \d+

cours_edit:
    pattern:  /{id}/editer
    requirements: 
        id: \d+
    defaults: { _controller: "KubEDTBundle:Cours:edit" }

cours_show:
    pattern:  /{id}
    requirements: 
        id: \d+
    defaults: { _controller: "KubEDTBundle:Cours:show" }