cours_create:
    pattern:  /add
    defaults: { _controller: "KubEDTBundle:Cours:create" }

cours_list:
    pattern:  /
    defaults: { _controller: "KubEDTBundle:Cours:list" }

cours_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KubEDTBundle:Cours:delete" }
    requirements: 
        id: \d+

cours_edit:
    pattern:  /{id}
    requirements: 
        id: \d+
    defaults: { _controller: "KubEDTBundle:Cours:edit" }