<?php

namespace Kub\CollaborationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRepository extends EntityRepository
{
}
