<?php

namespace Kub\CollaborationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{

	public function findByUser($user)
	{
		$qb = $this->createQueryBuilder('pro')
			->join('pro.permissions', 'p')
			->addSelect('p')

			->join('p.user', 'u')
			->addSelect('u')

			->where('u.id = :id')
			->setParameter('id', $user->getId())
		;

		return $qb->getQuery()->getResult();
	}

}
