<?php

namespace Kub\CollaborationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{

	public function findByUser($user)
	{
		$qb = $this->createQueryBuilder('pro')
			->join('pro.permissions', 'p')
			->addSelect('p')

			->join('p.user', 'u')
			->addSelect('u')

			->where('u.id = :id')
			->setParameter('id', $user->getId())
		;

		return $qb->getQuery()->getResult();
	}

	public function findOneOrNullBySlug($slug)
	{
		$qb = $this->createQueryBuilder('pro')
		->leftJoin('pro.permissions', 'p')
		->addSelect('p')

			->join('p.user', 'u')
			->addSelect('u')

		->leftJoin('pro.organisateur', 'org')
		->addSelect('org')

			->leftJoin('org.listeTaches', 'lt')
			->addSelect('lt')

				->leftJoin('lt.taches', 't')
				->addSelect('t')

					->leftJoin('t.participants', 'part')
					->addSelect('part')

		->leftJoin('pro.documentheque', 'doc')
		->addSelect('doc')

			->leftJoin('doc.ressources', 'r')
			->addSelect('r')

			->leftJoin('doc.fichiers', 'f')
			->addSelect('f')

		->where('pro.slug = :slug')
		->setParameter('slug', $slug)
		;
		
		return $qb->getQuery()->getOneOrNullResult();
	}

}
