<?php

namespace Kub\CollaborationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends EntityRepository
{

	public function findOneById($id)
	{
		$qb = $this->createQueryBuilder('t')
			->join('t.listeTaches', 'lt')
			->addSelect('lt')

			->join('lt.organisateur', 'o')
			->addSelect('o')

			->join('o.projet', 'pro')
			->addSelect('pro')

			->where('t.id = :id')
			->setParameter('id', $id)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}
}
