<?php

namespace Kub\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends UserRepository
{

	// fonction utilisee pour charger l'ensemble des données de l'utilisateur
	public function findWithAll($username)
	{
		$qb = $this->createQueryBuilder("e")
			->join('e.groupe', 'g')
			->addSelect('g')
			->join('e.niveau', 'n')
			->addSelect('n')
			->where("e.username = :username")
			->setParameter("username", $username)
		;

		return $qb->getQuery()->getResult();
	}

	public function findByNiveauName($niveau)
	{
		$qb = $this->createQueryBuilder("e")
			->join('e.niveau', 'n')
			->where("n.name = :niveau")
			->setParameter("niveau", $niveau)
		;

		return $qb->getQuery()->getResult();
	}
}
