<?php

namespace Kub\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends EntityRepository
{
}
