<?php

namespace Kub\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	public function getWithAll($username)
	{
		$qb = $this->createQueryBuilder("e")
			->where("e.username = :username")
			->setParameter("username", $username)
		;

		return $qb->getQuery()->getResult();
	}

}
