<?php

namespace Kub\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	public function finAllWithNames()
	{
		return $qb = $this->_em->createQuery("SELECT u.nom, u.prenom, u.username FROM Kub\UserBundle\Entity\User u ")->getArrayResult();
	}

}
