<?php

namespace Kub\RessourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceRepository extends EntityRepository
{
}
