<?php

namespace Kub\RessourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceRepository extends EntityRepository
{

	public function findByValide($valide)
	{
		$qb = $this->createQueryBuilder('r')
			->leftJoin('r.matiere', 'm')
			->addSelect('m')

			->leftJoin('r.niveau', 'n')
			->addSelect('n')

			->where('r.valide = :valide')
			->setParameter('valide', $valide)
		;

		return $qb->getQuery()->getResult();
	}

	public function findByValideAndUser($valide, $user)
	{
		$qb = $this->createQueryBuilder('r')
			->leftJoin('r.matiere', 'm')
			->addSelect('m')

			->leftJoin('r.niveau', 'n')
			->addSelect('n')

			->leftJoin('r.depositaire', 'd')
			->addSelect('d')

			->where('r.valide = :valide')
			->setParameter('valide', $valide)

			->andWhere('d.id = :id')
			->setParameter('id', $user->getId())
		;

		return $qb->getQuery()->getResult();
	}
}
