kub_collaboration_organisation:
    resource: "@KubCollaborationBundle/Resources/config/routing/organisation.yml"

kub_collaboration_communication:
    resource: "@KubCollaborationBundle/Resources/config/routing/communication.yml"

kub_collaboration_documentheque:
    resource: "@KubCollaborationBundle/Resources/config/routing/documentheque.yml"

kub_collaboration_homepage:
    pattern:  /
    defaults: { _controller: KubCollaborationBundle:Default:index }

kub_collaboration_projet_create:
    pattern:  /nouveau
    defaults: { _controller: KubCollaborationBundle:Projet:create }

kub_collaboration_projet_show:
    pattern:  /{slug}/
    defaults: { _controller: KubCollaborationBundle:Projet:show }

kub_collaboration_projet_edit:
    pattern:  /{slug}/gerer
    defaults: { _controller: KubCollaborationBundle:Projet:edit }

kub_collaboration_projet_delete:
    pattern:  /{slug}/supprimer
    defaults: { _controller: KubCollaborationBundle:Projet:delete }
