parameters:
#    kub_collaboration.example.class: Kub\CollaborationBundle\Example

services:
#    kub_collaboration.example:
#        class: %kub_collaboration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
