parameters:
#    kub_collaboration.example.class: Kub\CollaborationBundle\Example

services:
    kub_projet_voter:
        class: Kub\CollaborationBundle\Voter\ProjetVoter
        public: false
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: security.voter }