<?php

namespace Kub\NoteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\ClasseBundle\Entity\Groupe ;
use Kub\UserBundle\Entity\Professeur ;

/**
 * ControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleRepository extends EntityRepository
{

	public function findByProfesseurAndGroupe(Professeur $professeur, Groupe $groupe)
	{
		$qb = $this->createQueryBuilder("c")
			->join('c.professeur', 'p')
			->where('p.id = :id')
			->setParameter("id", $professeur->getId() )

			->leftJoin('c.notes', 'n')
			->join('n.eleve', 'e')
			->join('e.groupes', 'g')
			->andWhere('g.id = :g_id')
			->setParameter("g_id", $groupe->getId() )

			->orderBy('c.date', 'DESC')
		;

		return $qb->getQuery()->getResult();
	}

}
