<?php

namespace Kub\NoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Kub\ClasseBundle\Entity\Groupe ;
use Kub\UserBundle\Entity\Professeur ;
use Kub\UserBundle\Entity\Eleve ;

/**
 * ControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleRepository extends EntityRepository
{
	public function findOneById($id)
	{
		$qb = $this->createQueryBuilder('c')
			->leftJoin('c.professeur', 'p')
			->addSelect('p')
			->leftJoin('c.notes', 'n')
			->addSelect('n')
			->leftJoin('n.eleve', 'e')
			->addSelect('e')
			->leftJoin('c.cours', 'co')
			->addSelect('co')
			->leftJoin('co.groupes', 'g')
			->addSelect('g')

			->where('c.id = :id')
			->setParameter('id', $id )

			->orderBy('c.date', 'DESC')
		;

		return $qb->getQuery()->getSingleResult();
	}

	public function findByProfesseurAndGroupe(Professeur $professeur, Groupe $groupe)
	{
		$qb = $this->createQueryBuilder('c')
			->join('c.professeur', 'p')
			->where('p.id = :id')
			->setParameter('id', $professeur->getId() )

			->leftJoin('c.notes', 'n')
			->join('n.eleve', 'e')
			->join('e.groupes', 'g')
			->andWhere('g.id = :g_id')
			->setParameter('g_id', $groupe->getId() )

			->orderBy('c.date', 'DESC')
		;

		return $qb->getQuery()->getResult();
	}

	public function findOneByUserGroupsAndProfesseur(Eleve $eleve, Professeur $professeur)
	{
		$qb = $this->createQueryBuilder('c')
			->join('c.cours', 'co')
			->addSelect('co')

			->join('co.matiere', 'm')
			->addSelect('m')

			->join('c.professeur', 'p')
			->where('p.id = :id')
			->setParameter('id', $professeur->getId() )

			->join('c.notes', 'n')
			->join('n.eleve', 'e')
			->join('e.groupes', 'g')
			->join('g.eleves', 'el')
			->andWhere('el.id = :el_id')
			->setParameter('el_id', $eleve->getId() )

			->orderBy('c.date', 'DESC')
		;

		return $qb->getQuery()->getResult();
	}

}
