<?php

namespace Kub\NoteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\UserBundle\Entity\Eleve ;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
}
