<?php

namespace Kub\NoteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Kub\UserBundle\Entity\Eleve ;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
	public function findMoyennesFor($username)
	{
		$qb = $this->_em->createQuery('
			SELECT AVG(n.note / n.coefficient) * 20 AS note, m.name AS matiere FROM KubNoteBundle:Note n
			JOIN n.eleve e
			JOIN n.controle c
			JOIN c.cours co
			JOIN co.matiere m
			WHERE e.username = :username
			GROUP BY m.name
		')
		->setParameter('username', $username);
		;

		return $qb->getArrayResult();
	}

	public function findByUsername($username)
	{
		$qb = $this->_em->createQuery("
			SELECT  m.name AS matiere, n AS note, c, co, p FROM KubNoteBundle:Note n

			JOIN n.eleve e
			JOIN n.controle c
			JOIN c.cours co
			JOIN co.matiere m
			JOIN co.professeur p

			WHERE e.username = :username
		")
		->setParameter("username", $username)
		;

		return $qb->getArrayResult();	
	}

	public function findOneByControleIdAndEleveId($controle_id, $eleve_id)
	{
		$qb = $this->_em->createQuery("
			SELECT n, c, p FROM KubNoteBundle:Note n

			JOIN n.eleve e
			JOIN n.controle c
			JOIN c.professeur p

			WHERE c.id = :controle_id
			AND   e.id = :eleve_id
		")
		->setParameter("controle_id", $controle_id)
		->setParameter("eleve_id", $eleve_id)
		;

		return $qb->getOneOrNullResult();	
	}
}
