<?php

namespace Kub\MessagerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageUserRepository extends EntityRepository
{

	public function findByUserAndThreadId($user, $threadId){

		$qb = $this->createQueryBuilder('mu')
			->join('mu.user', 'u')
			->where('u.id = :u_id')
			->setParameter('u_id', $user->getId())

			->join('mu.message', 'm')
			->join('m.thread', 't')
			->Andwhere('t.id = :t_id')
			->setParameter('t_id', $threadId)
		;

		return $qb->getQuery()->getResult();
	}

}
