<?php

namespace Kub\MessagerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{

	public function findByUser($user)
	{
		$qb = $this->createQueryBuilder('t')
			->join('t.messages', 'm')
			->addSelect('m')

			->join('m.messageUser', 'mu')
			->addSelect('mu')

			->join('mu.user', 'u')
			->addSelect('u')

			->where('u.id = :u_id')
			->setParameter('u_id', $user->getId())
		;

		return $qb->getQuery()->getResult();
	}

	public function findOneById($id)
	{
		$qb = $this->createQueryBuilder('t')
			->join('t.messages', 'm')
			->addSelect('m')

			->join('m.messageUser', 'mu')
			->addSelect('mu')

			->join('mu.user', 'u')
			->addSelect('u')

			->where('mu.readed = true')

			->where('t.id = :id')
			->setParameter('id', $id)
		;

		return $qb->getQuery()->getSingleResult();
	}

}
