parameters:
#    kub_agenda.example.class: Kub\AgendaBundle\Example

services:
#    kub_agenda.example:
#        class: %kub_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
